% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={HAMED OBEIDAT},
  pdfauthor={hamed obeidat},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{HAMED OBEIDAT}
\author{hamed obeidat}
\date{2026-02-22}

\begin{document}
\maketitle

A study on the cell life cycle: A random sample of cells was taken to
measure the effect of external factors such as temperature and
carbohydrate consumption rate on the cell life cycle, and to study the
differences between these factors.

\begin{verbatim}
##                                                                             
## 1 function (..., list = character(), package = NULL, lib.loc = NULL,        
## 2     verbose = getOption("verbose"), envir = .GlobalEnv, overwrite = TRUE) 
## 3 {                                                                         
## 4     fileExt <- function(x) {                                              
## 5         db <- grepl("\\\\.[^.]+\\\\.(gz|bz2|xz)$", x)                     
## 6         ans <- sub(".*\\\\.", "", x)
\end{verbatim}

Table one : shows the number of study variables and the number of
individuals.

\begin{verbatim}
##     V1  V2 V3
## 1  150 0.6 10
## 2   86 1.0 10
## 3   49 1.4 10
## 4  288 0.6 20
## 5  157 1.0 20
## 6  131 1.0 20
## 7  184 1.0 20
## 8  109 1.4 20
## 9  279 0.6 30
## 10 235 1.0 30
## 11 224 1.4 30
\end{verbatim}

\begin{verbatim}
## [1] 11  3
\end{verbatim}

\begin{verbatim}
## 'data.frame':    11 obs. of  3 variables:
##  $ V1: int  150 86 49 288 157 131 184 109 279 235 ...
##  $ V2: num  0.6 1 1.4 0.6 1 1 1 1.4 0.6 1 ...
##  $ V3: int  10 10 10 20 20 20 20 20 30 30 ...
\end{verbatim}

\begin{longtable}[]{@{}llll@{}}
\caption{The Descriptive Statistic for Data}\tabularnewline
\toprule\noalign{}
& life & chrate & temp \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& life & chrate & temp \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
& Min. : 49.0 & Min. :0.6 & 10:3 \\
& 1st Qu.:120.0 & 1st Qu.:0.8 & 20:5 \\
& Median :157.0 & Median :1.0 & 30:3 \\
& Mean :172.0 & Mean :1.0 & NA \\
& 3rd Qu.:229.5 & 3rd Qu.:1.2 & NA \\
& Max. :288.0 & Max. :1.4 & NA \\
\end{longtable}

Table two: shows that the mean value of the variable (life) is equal to
172 and And greater value is 288 and Smallest value is 49 , The results
show a significant deviation in the values, indicating a lack of
homogeneity,In terms of chrate carbohydrate intake, it appears that
carbohydrate consumption values are homogeneous, with the highest value
reaching {[}a certain level{]} is 1.4 and lowest levels is 0.6 , The
number of cells at 10 degrees Celsius was 3, the number of cells at 20
degrees Celsius was 5, and the number of cells at 30 degrees Celsius was
3.

\pandocbounded{\includegraphics[keepaspectratio]{ANCOVA_files/figure-latex/unnamed-chunk-3-1.pdf}}
The graph shows that the average cell lifespan at 30 degrees is greater
than at 10 and 20 degrees.

Inference statistic:

\begin{verbatim}
## ANOVA Table (type II tests)
## 
##   Effect DFn DFd      F     p p<.05   ges
## 1 chrate   1   7 17.069 0.004     * 0.709
## 2   temp   2   7 15.619 0.003     * 0.817
\end{verbatim}

\begin{longtable}[]{@{}lrrrrlr@{}}
\caption{ANOVA Table}\tabularnewline
\toprule\noalign{}
Effect & DFn & DFd & F & p & p\textless.05 & ges \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Effect & DFn & DFd & F & p & p\textless.05 & ges \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
chrate & 1 & 7 & 17.069 & 0.004 & * & 0.709 \\
temp & 2 & 7 & 15.619 & 0.003 & * & 0.817 \\
\end{longtable}

The results showed that there were statistically significant differences
amounting to a value p-value of chrate is 0.004 less than This suggests
that carbohydrate levels had an effect on cell life It has an effect on
modeling,The results showed that there were statistically significant
differences between the average temperatures, where the value reached
p-value is 0.003 less than 0.05

Check the assumption:

\pandocbounded{\includegraphics[keepaspectratio]{ANCOVA_files/figure-latex/unnamed-chunk-5-1.pdf}}
The diagram showed that there is a strong negative linear relationship
between cell life and carbohydrate content at 10°C The carbohydrate
content explained 0.98\% of the variation in cell life, meaning it had a
significant impact,At a temperature of 20, the model interprets its
ratio is 0.82 This indicates that the rate of carbohydrate consumption
explains 0.82\% of cell life, At a temperature of 30 degrees, the rate
of carbohydrate consumption was interpreted as follows is 0.89.

\pandocbounded{\includegraphics[keepaspectratio]{ANCOVA_files/figure-latex/unnamed-chunk-6-1.pdf}}
Residuals vs fitted plot showed random scatter,indicating linearity and
constant variance assumptions were reasonably met, The Normal Q-Qplot
showed points far away the line ,not normall distrbution Scale-location
not homogeneous because the points are not distributed horizontally.
Residuals vs leverage plot showed that the points are inside shape , no
influential points .

\end{document}
